# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/preischadt/clones/IA-Proj1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/preischadt/clones/IA-Proj1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/preischadt/clones/IA-Proj1/CMakeFiles /home/preischadt/clones/IA-Proj1/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/preischadt/clones/IA-Proj1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named IA_Proj1

# Build rule for target.
IA_Proj1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 IA_Proj1
.PHONY : IA_Proj1

# fast build rule for target.
IA_Proj1/fast:
	$(MAKE) -f CMakeFiles/IA_Proj1.dir/build.make CMakeFiles/IA_Proj1.dir/build
.PHONY : IA_Proj1/fast

src/Benchmark.o: src/Benchmark.cpp.o

.PHONY : src/Benchmark.o

# target to build an object file
src/Benchmark.cpp.o:
	$(MAKE) -f CMakeFiles/IA_Proj1.dir/build.make CMakeFiles/IA_Proj1.dir/src/Benchmark.cpp.o
.PHONY : src/Benchmark.cpp.o

src/Benchmark.i: src/Benchmark.cpp.i

.PHONY : src/Benchmark.i

# target to preprocess a source file
src/Benchmark.cpp.i:
	$(MAKE) -f CMakeFiles/IA_Proj1.dir/build.make CMakeFiles/IA_Proj1.dir/src/Benchmark.cpp.i
.PHONY : src/Benchmark.cpp.i

src/Benchmark.s: src/Benchmark.cpp.s

.PHONY : src/Benchmark.s

# target to generate assembly for a file
src/Benchmark.cpp.s:
	$(MAKE) -f CMakeFiles/IA_Proj1.dir/build.make CMakeFiles/IA_Proj1.dir/src/Benchmark.cpp.s
.PHONY : src/Benchmark.cpp.s

src/Coordinate.o: src/Coordinate.cpp.o

.PHONY : src/Coordinate.o

# target to build an object file
src/Coordinate.cpp.o:
	$(MAKE) -f CMakeFiles/IA_Proj1.dir/build.make CMakeFiles/IA_Proj1.dir/src/Coordinate.cpp.o
.PHONY : src/Coordinate.cpp.o

src/Coordinate.i: src/Coordinate.cpp.i

.PHONY : src/Coordinate.i

# target to preprocess a source file
src/Coordinate.cpp.i:
	$(MAKE) -f CMakeFiles/IA_Proj1.dir/build.make CMakeFiles/IA_Proj1.dir/src/Coordinate.cpp.i
.PHONY : src/Coordinate.cpp.i

src/Coordinate.s: src/Coordinate.cpp.s

.PHONY : src/Coordinate.s

# target to generate assembly for a file
src/Coordinate.cpp.s:
	$(MAKE) -f CMakeFiles/IA_Proj1.dir/build.make CMakeFiles/IA_Proj1.dir/src/Coordinate.cpp.s
.PHONY : src/Coordinate.cpp.s

src/Graph.o: src/Graph.cpp.o

.PHONY : src/Graph.o

# target to build an object file
src/Graph.cpp.o:
	$(MAKE) -f CMakeFiles/IA_Proj1.dir/build.make CMakeFiles/IA_Proj1.dir/src/Graph.cpp.o
.PHONY : src/Graph.cpp.o

src/Graph.i: src/Graph.cpp.i

.PHONY : src/Graph.i

# target to preprocess a source file
src/Graph.cpp.i:
	$(MAKE) -f CMakeFiles/IA_Proj1.dir/build.make CMakeFiles/IA_Proj1.dir/src/Graph.cpp.i
.PHONY : src/Graph.cpp.i

src/Graph.s: src/Graph.cpp.s

.PHONY : src/Graph.s

# target to generate assembly for a file
src/Graph.cpp.s:
	$(MAKE) -f CMakeFiles/IA_Proj1.dir/build.make CMakeFiles/IA_Proj1.dir/src/Graph.cpp.s
.PHONY : src/Graph.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/IA_Proj1.dir/build.make CMakeFiles/IA_Proj1.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/IA_Proj1.dir/build.make CMakeFiles/IA_Proj1.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/IA_Proj1.dir/build.make CMakeFiles/IA_Proj1.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... IA_Proj1"
	@echo "... src/Benchmark.o"
	@echo "... src/Benchmark.i"
	@echo "... src/Benchmark.s"
	@echo "... src/Coordinate.o"
	@echo "... src/Coordinate.i"
	@echo "... src/Coordinate.s"
	@echo "... src/Graph.o"
	@echo "... src/Graph.i"
	@echo "... src/Graph.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

